name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Release build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --all-features
    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --verbose
    - name: Check if can be packaged
      uses: actions-rs/cargo@v1
      with:
        command: package
        args: -p netconfig
